/*
Copyright 2013 Kommunal- og regionaldepartementet.

This file is part of minsak.no.

Minsak.no is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License version 3 as published by the Free Software Foundation.

Minsak.no is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with minsak.no. If not, see http://www.gnu.org/licenses/gpl-3.0.html.
*/


set names utf8;
INSERT INTO `user` (name, username, isSiteadmin) VALUES ('test', 'test@localhost', 1);

INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1,'Østfold',NULL,'nb','oestfold', 500);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (2,'Akershus',NULL,'nb','akershus', 500);
-- INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (3,'Oslo',NULL,'nb','oslo-f', 500);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (4,'Hedmark',NULL,'nb','hedmark', 500);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (5,'Oppland',NULL,'nb','oppland', 500);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (6,'Buskerud',NULL,'nb','buskerud', 500);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (7,'Vestfold',NULL,'nb','vestfold', 500);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (8,'Telemark',NULL,'nb','telemark', 500);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (9,'Aust-Agder',NULL,'nb','aust-agder', 500);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (10,'Vest-Agder',NULL,'nb','vest-agder', 500);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (11,'Rogaland',NULL,'nb','rogaland', 500);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (12,'Hordaland',NULL,'nb','hordaland', 500);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (14,'Sogn og fjordane',NULL,'nb','sogn-og-fjordane', 500);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (15,'Møre og Romsdal',NULL,'nb','moere-og-romsdal', 500);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (16,'Sør-Trøndelag',NULL,'nb','soer-troendelag', 500);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (17,'Nord-Trøndelag',NULL,'nb','nord-troendelag', 500);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (18,'Nordland',NULL,'nb','nordland', 500);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (19,'Troms',NULL,'nb','troms', 500);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (20,'Finnmark',NULL,'nb','finnmark', 500);

INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (101, 'Halden', 1, 'nb', 'halden', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (104, 'Moss', 1, 'nb', 'moss', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (105, 'Sarpsborg', 1, 'nb', 'sarpsborg', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (106, 'Fredrikstad', 1, 'nb', 'fredrikstad', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (111, 'Hvaler', 1, 'nb', 'hvaler', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (118, 'Aremark', 1, 'nb', 'aremark', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (119, 'Marker', 1, 'nb', 'marker', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (121, 'Rømskog', 1, 'nb', 'roemskog', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (122, 'Trøgstad', 1, 'nb', 'troegstad', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (123, 'Spydeberg', 1, 'nb', 'spydeberg', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (124, 'Askim', 1, 'nb', 'askim', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (125, 'Eidsberg', 1, 'nb', 'eidsberg', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (127, 'Skiptvet', 1, 'nb', 'skiptvet', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (128, 'Rakkestad', 1, 'nb', 'rakkestad', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (135, 'Råde', 1, 'nb', 'raade', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (136, 'Rygge', 1, 'nb', 'rygge', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (137, 'Våler', 1, 'nb', 'valer-of', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (138, 'Hobøl', 1, 'nb', 'hoboel', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (211, 'Vestby', 2, 'nb', 'vestby', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (213, 'Ski', 2, 'nb', 'ski', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (214, 'Ås', 2, 'nb', 'aas', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (215, 'Frogn', 2, 'nb', 'frogn', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (216, 'Nesodden', 2, 'nb', 'nesodden', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (217, 'Oppegård', 2, 'nb', 'oppegaard', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (219, 'Bærum', 2, 'nb', 'baerum', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (220, 'Asker', 2, 'nb', 'asker', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (221, 'Aurskog-Høland', 2, 'nb', 'aurskog-hoeland', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (226, 'Sørum', 2, 'nb', 'soerum', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (227, 'Fet', 2, 'nb', 'fet', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (228, 'Rælingen', 2, 'nb', 'raelingen', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (229, 'Enebakk', 2, 'nb', 'enebakk', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (230, 'Lørenskog', 2, 'nb', 'loerenskog', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (231, 'Skedsmo', 2, 'nb', 'skedsmo', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (233, 'Nittedal', 2, 'nb', 'nittedal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (234, 'Gjerdrum', 2, 'nb', 'gjerdrum', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (235, 'Ullensaker', 2, 'nb', 'ullensaker', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (236, 'Nes', 2, 'nb', 'nes-ak', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (237, 'Eidsvoll', 2, 'nb', 'eidsvoll', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (238, 'Nannestad', 2, 'nb', 'nannestad', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (239, 'Hurdal', 2, 'nb', 'hurdal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (301, 'Oslo', NULL, 'nb', 'oslo', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (402, 'Kongsvinger', 4, 'nb', 'kongsvinger', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (403, 'Hamar', 4, 'nb', 'hamar', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (412, 'Ringsaker', 4, 'nb', 'ringsaker', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (415, 'Løten', 4, 'nb', 'loeten', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (417, 'Stange', 4, 'nb', 'stange', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (418, 'Nord-Odal', 4, 'nb', 'nord-odal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (419, 'Sør-Odal', 4, 'nb', 'soer-odal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (420, 'Eidskog', 4, 'nb', 'eidskog', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (423, 'Grue', 4, 'nb', 'grue', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (425, 'Åsnes', 4, 'nb', 'aasnes', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (426, 'Våler', 4, 'nb', 'vaaler-he', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (427, 'Elverum', 4, 'nb', 'elverum', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (428, 'Trysil', 4, 'nb', 'trysil', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (429, 'Åmot', 4, 'nb', 'aamot', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (430, 'Stor-Elvdal', 4, 'nb', 'stor-elvdal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (432, 'Rendalen', 4, 'nb', 'rendalen', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (434, 'Engerdal', 4, 'nb', 'engerdal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (436, 'Tolga', 4, 'nb', 'tolga', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (437, 'Tynset', 4, 'nb', 'tynset', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (438, 'Alvdal', 4, 'nb', 'alvdal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (439, 'Folldal', 4, 'nb', 'folldal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (441, 'Os', 4, 'nb', 'os-he', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (501, 'Lillehammer', 5, 'nb', 'lillehammer', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (502, 'Gjøvik', 5, 'nb', 'gjoevik', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (511, 'Dovre', 5, 'nb', 'dovre', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (512, 'Lesja', 5, 'nb', 'lesja', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (513, 'Skjåk', 5, 'nn', 'skjaak', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (514, 'Lom', 5, 'nn', 'lom', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (515, 'Vågå', 5, 'nn', 'vaagaa', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (516, 'Nord-Fron', 5, 'nn', 'nord-fron', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (517, 'Sel', 5, 'nb', 'sel', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (519, 'Sør-Fron', 5, 'nb', 'soer-fron', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (520, 'Ringebu', 5, 'nb', 'ringebu', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (521, 'Øyer', 5, 'nb', 'oeyer', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (522, 'Gausdal', 5, 'nb', 'gausdal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (528, 'Østre Toten', 5, 'nb', 'oestre-toten', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (529, 'Vestre Toten', 5, 'nb', 'vestre-toten', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (532, 'Jevnaker', 5, 'nb', 'jevnaker', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (533, 'Lunner', 5, 'nb', 'lunner', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (534, 'Gran', 5, 'nb', 'gran', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (536, 'Søndre Land', 5, 'nb', 'soendre-land', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (538, 'Nordre Land', 5, 'nb', 'nordre-land', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (540, 'Sør-Aurdal', 5, 'nb', 'soer-aurdal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (541, 'Etnedal', 5, 'nb', 'etnedal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (542, 'Nord-Aurdal', 5, 'nb', 'nord-aurdal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (543, 'Vestre Slidre', 5, 'nn', 'vestre-slidre', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (544, 'Øystre Slidre', 5, 'nn', 'oeystre-slidre', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (545, 'Vang', 5, 'nn', 'vang', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (602, 'Drammen', 6, 'nb', 'drammen', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (604, 'Kongsberg', 6, 'nb', 'kongsberg', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (605, 'Ringerike', 6, 'nb', 'ringerike', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (612, 'Hole', 6, 'nb', 'hole', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (615, 'Flå', 6, 'nb', 'flaa', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (616, 'Nes', 6, 'nb', 'nes-bu', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (617, 'Gol', 6, 'nn', 'gol', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (618, 'Hemsedal', 6, 'nn', 'hemsedal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (619, 'Ål', 6, 'nn', 'aal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (620, 'Hol', 6, 'nb', 'hol', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (621, 'Sigdal', 6, 'nb', 'sigdal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (622, 'Krødsherad', 6, 'nb', 'kroedsherad', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (623, 'Modum', 6, 'nb', 'modum', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (624, 'Øvre Eiker', 6, 'nb', 'oevre-eiker', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (625, 'Nedre Eiker', 6, 'nb', 'nedre-eiker', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (626, 'Lier', 6, 'nb', 'lier', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (627, 'Røyken', 6, 'nb', 'roeyken', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (628, 'Hurum', 6, 'nb', 'hurum', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (631, 'Flesberg', 6, 'nb', 'flesberg', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (632, 'Rollag', 6, 'nb', 'rollag', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (633, 'Nore og Uvdal', 6, 'nb', 'nore-og-uvdal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (701, 'Horten', 7, 'nb', 'horten', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (702, 'Holmestrand', 7, 'nb', 'holmestrand', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (704, 'Tønsberg', 7, 'nb', 'toensberg', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (706, 'Sandefjord', 7, 'nb', 'sandefjord', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (709, 'Larvik', 7, 'nb', 'larvik', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (711, 'Svelvik', 7, 'nb', 'svelvik', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (713, 'Sande', 7, 'nb', 'sande-ve', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (714, 'Hof', 7, 'nb', 'hof', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (716, 'Re', 7, 'nb', 're', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (719, 'Andebu', 7, 'nb', 'andebu', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (720, 'Stokke', 7, 'nb', 'stokke', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (722, 'Nøtterøy', 7, 'nb', 'noetteroey', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (723, 'Tjøme', 7, 'nb', 'tjoeme', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (728, 'Lardal', 7, 'nb', 'lardal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (805, 'Porsgrunn', 8, 'nb', 'porsgrunn', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (806, 'Skien', 8, 'nb', 'skien', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (807, 'Notodden', 8, 'nb', 'notodden', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (811, 'Siljan', 8, 'nb', 'siljan', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (814, 'Bamble', 8, 'nb', 'bamble', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (815, 'Kragerø', 8, 'nb', 'krageroe', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (817, 'Drangedal', 8, 'nb', 'drangedal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (819, 'Nome', 8, 'nb', 'nome', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (821, 'Bø', 8, 'nn', 'boe-te', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (822, 'Sauherad', 8, 'nb', 'sauherad', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (826, 'Tinn', 8, 'nb', 'tinn', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (827, 'Hjartdal', 8, 'nn', 'hjartdal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (828, 'Seljord', 8, 'nn', 'seljord', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (829, 'Kviteseid', 8, 'nn', 'kviteseid', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (830, 'Nissedal', 8, 'nn', 'nissedal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (831, 'Fyresdal', 8, 'nn', 'fyresdal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (833, 'Tokke', 8, 'nn', 'tokke', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (834, 'Vinje', 8, 'nn', 'vinje', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (901, 'Risør', 9, 'nb', 'risoer', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (904, 'Grimstad', 9, 'nb', 'grimstad', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (906, 'Arendal', 9, 'nb', 'arendal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (911, 'Gjerstad', 9, 'nb', 'gjerstad', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (912, 'Vegårshei', 9, 'nb', 'vegaarshei', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (914, 'Tvedestrand', 9, 'nb', 'tvedestrand', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (919, 'Froland', 9, 'nb', 'froland', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (926, 'Lillesand', 9, 'nb', 'lillesand', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (928, 'Birkenes', 9, 'nb', 'birkenes', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (929, 'Åmli', 9, 'nn', 'aamli', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (935, 'Iveland', 9, 'nb', 'iveland', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (937, 'Evje og Hornnes', 9, 'nb', 'evje-og-hornnes', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (938, 'Bygland', 9, 'nn', 'bygland', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (940, 'Valle', 9, 'nn', 'valle', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (941, 'Bykle', 9, 'nb', 'bykle', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1001, 'Kristiansand', 10, 'nb', 'kristiansand', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1002, 'Mandal', 10, 'nb', 'mandal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1003, 'Farsund', 10, 'nb', 'farsund', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1004, 'Flekkefjord', 10, 'nb', 'flekkefjord', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1014, 'Vennesla', 10, 'nb', 'vennesla', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1017, 'Songdalen', 10, 'nb', 'songdalen', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1018, 'Søgne', 10, 'nb', 'soegne', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1021, 'Marnardal', 10, 'nb', 'marnardal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1026, 'Åseral', 10, 'nn', 'aaseral', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1027, 'Audnedal', 10, 'nb', 'audnedal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1029, 'Lindesnes', 10, 'nb', 'lindesnes', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1032, 'Lyngdal', 10, 'nb', 'lyngdal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1034, 'Hægebostad', 10, 'nn', 'haegebostad', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1037, 'Kvinesdal', 10, 'nb', 'kvinesdal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1046, 'Sirdal', 10, 'nb', 'sirdal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1101, 'Eigersund', 11, 'nb', 'eigersund', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1102, 'Sandnes', 11, 'nb', 'sandnes', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1103, 'Stavanger', 11, 'nb', 'stavanger', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1106, 'Haugesund', 11, 'nb', 'haugesund', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1111, 'Sokndal', 11, 'nb', 'sokndal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1112, 'Lund', 11, 'nb', 'lund', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1114, 'Bjerkreim', 11, 'nn', 'bjerkreim', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1119, 'Hå', 11, 'nb', 'haa', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1120, 'Klepp', 11, 'nn', 'klepp', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1121, 'Time', 11, 'nn', 'time', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1122, 'Gjesdal', 11, 'nb', 'gjesdal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1124, 'Sola', 11, 'nb', 'sola', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1127, 'Randaberg', 11, 'nb', 'randaberg', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1129, 'Forsand', 11, 'nn', 'forsand', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1130, 'Strand', 11, 'nb', 'strand', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1133, 'Hjelmeland', 11, 'nn', 'hjelmeland', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1134, 'Suldal', 11, 'nn', 'suldal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1135, 'Sauda', 11, 'nn', 'sauda', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1141, 'Finnøy', 11, 'nn', 'finnoey', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1142, 'Rennesøy', 11, 'nb', 'rennesoey', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1144, 'Kvitsøy', 11, 'nb', 'kvitsoey', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1145, 'Bokn', 11, 'nn', 'bokn', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1146, 'Tysvær', 11, 'nn', 'tysvaer', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1149, 'Karmøy', 11, 'nb', 'karmoey', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1151, 'Utsira', 11, 'nb', 'utsira', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1160, 'Vindafjord', 11, 'nb', 'vindafjord', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1201, 'Bergen', 12, 'nb', 'bergen', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1211, 'Etne', 12, 'nn', 'etne', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1216, 'Sveio', 12, 'nn', 'sveio', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1219, 'Bømlo', 12, 'nn', 'boemlo', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1221, 'Stord', 12, 'nn', 'stord', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1222, 'Fitjar', 12, 'nn', 'fitjar', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1223, 'Tysnes', 12, 'nn', 'tysnes', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1224, 'Kvinnherad', 12, 'nn', 'kvinnherad', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1227, 'Jondal', 12, 'nn', 'jondal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1228, 'Odda', 12, 'nb', 'odda', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1231, 'Ullensvang', 12, 'nn', 'ullensvang', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1232, 'Eidfjord', 12, 'nn', 'eidfjord', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1233, 'Ulvik', 12, 'nn', 'ulvik', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1234, 'Granvin', 12, 'nn', 'granvin', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1235, 'Voss', 12, 'nn', 'voss', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1238, 'Kvam', 12, 'nn', 'kvam', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1241, 'Fusa', 12, 'nn', 'fusa', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1242, 'Samnanger', 12, 'nn', 'samnanger', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1243, 'Os', 12, 'nn', 'os-ho', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1244, 'Austevoll', 12, 'nn', 'austevoll', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1245, 'Sund', 12, 'nn', 'sund', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1246, 'Fjell', 12, 'nb', 'fjell', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1247, 'Askøy', 12, 'nb', 'askoey', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1251, 'Vaksdal', 12, 'nn', 'vaksdal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1252, 'Modalen', 12, 'nn', 'modalen', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1253, 'Osterøy', 12, 'nn', 'osteroey', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1256, 'Meland', 12, 'nn', 'meland', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1259, 'Øygarden', 12, 'nn', 'oeygarden', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1260, 'Radøy', 12, 'nn', 'radoey', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1263, 'Lindås', 12, 'nn', 'lindaas', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1264, 'Austrheim', 12, 'nn', 'austrheim', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1265, 'Fedje', 12, 'nn', 'fedje', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1266, 'Masfjorden', 12, 'nn', 'masfjorden', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1401, 'Flora', 14, 'nn', 'flora', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1411, 'Gulen', 14, 'nn', 'gulen', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1412, 'Solund', 14, 'nn', 'solund', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1413, 'Hyllestad', 14, 'nn', 'hyllestad', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1416, 'Høyanger', 14, 'nn', 'hoeyanger', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1417, 'Vik', 14, 'nn', 'vik', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1418, 'Balestrand', 14, 'nn', 'balestrand', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1419, 'Leikanger', 14, 'nb', 'leikanger', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1420, 'Sogndal', 14, 'nn', 'sogndal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1421, 'Aurland', 14, 'nn', 'aurland', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1422, 'Lærdal', 14, 'nn', 'laerdal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1424, 'Årdal', 14, 'nn', 'aardal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1426, 'Luster', 14, 'nn', 'luster', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1428, 'Askvoll', 14, 'nn', 'askvoll', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1429, 'Fjaler', 14, 'nn', 'fjaler', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1430, 'Gaular', 14, 'nn', 'gaular', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1431, 'Jølster', 14, 'nn', 'joelster', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1432, 'Førde', 14, 'nn', 'foerde', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1433, 'Naustdal', 14, 'nn', 'naustdal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1438, 'Bremanger', 14, 'nn', 'bremanger', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1439, 'Vågsøy', 14, 'nn', 'vaagsoey', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1441, 'Selje', 14, 'nn', 'selje', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1443, 'Eid', 14, 'nn', 'eid', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1444, 'Hornindal', 14, 'nn', 'hornindal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1445, 'Gloppen', 14, 'nn', 'gloppen', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1449, 'Stryn', 14, 'nn', 'stryn', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1502, 'Molde', 15, 'nb', 'molde', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1504, 'Ålesund', 15, 'nb', 'aalesund', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1505, 'Kristiansund', 15, 'nb', 'kristiansund', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1511, 'Vanylven', 15, 'nn', 'vanylven', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1514, 'Sande', 15, 'nn', 'sande-mr', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1515, 'Herøy', 15, 'nn', 'heroy-mr', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1516, 'Ulstein', 15, 'nn', 'ulstein', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1517, 'Hareid', 15, 'nn', 'hareid', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1519, 'Volda', 15, 'nn', 'volda', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1520, 'Ørsta', 15, 'nn', 'oersta', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1523, 'Ørskog', 15, 'nn', 'oerskog', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1524, 'Norddal', 15, 'nn', 'norddal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1525, 'Stranda', 15, 'nn', 'stranda', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1526, 'Stordal', 15, 'nn', 'stordal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1528, 'Sykkylven', 15, 'nn', 'sykkylven', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1529, 'Skodje', 15, 'nn', 'skodje', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1531, 'Sula', 15, 'nn', 'sula', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1532, 'Giske', 15, 'nn', 'giske', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1534, 'Haram', 15, 'nn', 'haram', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1535, 'Vestnes', 15, 'nn', 'vestnes', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1539, 'Rauma', 15, 'nb', 'rauma', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1543, 'Nesset', 15, 'nb', 'nesset', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1545, 'Midsund', 15, 'nn', 'midsund', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1546, 'Sandøy', 15, 'nn', 'sandoey', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1547, 'Aukra', 15, 'nn', 'aukra', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1548, 'Fræna', 15, 'nn', 'fraena', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1551, 'Eide', 15, 'nb', 'eide', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1554, 'Averøy', 15, 'nb', 'averoey', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1557, 'Gjemnes', 15, 'nb', 'gjemnes', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1560, 'Tingvoll', 15, 'nb', 'tingvoll', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1563, 'Sunndal', 15, 'nb', 'sunndal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1566, 'Surnadal', 15, 'nn', 'surnadal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1567, 'Rindal', 15, 'nb', 'rindal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1571, 'Halsa', 15, 'nb', 'halsa', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1573, 'Smøla', 15, 'nb', 'smoela', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1576, 'Aure', 15, 'nb', 'aure', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1601, 'Trondheim', 16, 'nb', 'trondheim', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1612, 'Hemne', 16, 'nb', 'hemne', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1613, 'Snillfjord', 16, 'nb', 'snillfjord', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1617, 'Hitra', 16, 'nb', 'hitra', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1620, 'Frøya', 16, 'nb', 'froeya', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1621, 'Ørland', 16, 'nb', 'oerland', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1622, 'Agdenes', 16, 'nb', 'agdenes', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1624, 'Rissa', 16, 'nb', 'rissa', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1627, 'Bjugn', 16, 'nb', 'bjugn', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1630, 'Åfjord', 16, 'nb', 'aafjord', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1632, 'Roan', 16, 'nb', 'roan', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1633, 'Osen', 16, 'nb', 'osen', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1634, 'Oppdal', 16, 'nb', 'oppdal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1635, 'Rennebu', 16, 'nb', 'rennebu', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1636, 'Meldal', 16, 'nb', 'meldal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1638, 'Orkdal', 16, 'nb', 'orkdal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1640, 'Røros', 16, 'nb', 'roeros', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1644, 'Holtålen', 16, 'nb', 'holtaalen', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1648, 'Midtre Gauldal', 16, 'nb', 'midtre-gauldal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1653, 'Melhus', 16, 'nb', 'melhus', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1657, 'Skaun', 16, 'nb', 'skaun', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1662, 'Klæbu', 16, 'nb', 'klaebu', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1663, 'Malvik', 16, 'nb', 'malvik', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1664, 'Selbu', 16, 'nb', 'selbu', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1665, 'Tydal', 16, 'nb', 'tydal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1702, 'Steinkjer', 17, 'nb', 'steinkjer', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1703, 'Namsos', 17, 'nb', 'namsos', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1711, 'Meråker', 17, 'nb', 'meraaker', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1714, 'Stjørdal', 17, 'nb', 'stjoerdal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1717, 'Frosta', 17, 'nb', 'frosta', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1718, 'Leksvik', 17, 'nb', 'leksvik', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1719, 'Levanger', 17, 'nb', 'levanger', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1721, 'Verdal', 17, 'nb', 'verdal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1723, 'Mosvik', 17, 'nb', 'mosvik', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1724, 'Verran', 17, 'nb', 'verran', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1725, 'Namdalseid', 17, 'nb', 'namdalseid', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1729, 'Inderøy', 17, 'nb', 'inderoey', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1736, 'Snåsa', 17, 'nb', 'snaasa', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1738, 'Lierne', 17, 'nb', 'lierne', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1739, 'Røyrvik', 17, 'nb', 'roeyrvik', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1740, 'Namsskogan', 17, 'nb', 'namsskogan', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1742, 'Grong', 17, 'nb', 'grong', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1743, 'Høylandet', 17, 'nb', 'hoeylandet', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1744, 'Overhalla', 17, 'nb', 'overhalla', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1748, 'Fosnes', 17, 'nb', 'fosnes', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1749, 'Flatanger', 17, 'nb', 'flatanger', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1750, 'Vikna', 17, 'nb', 'vikna', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1751, 'Nærøy', 17, 'nb', 'naeroey', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1755, 'Leka', 17, 'nb', 'leka', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1804, 'Bodø', 18, 'nb', 'bodoe', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1805, 'Narvik', 18, 'nb', 'narvik', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1811, 'Bindal', 18, 'nb', 'bindal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1812, 'Sømna', 18, 'nb', 'soemna', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1813, 'Brønnøy', 18, 'nb', 'broennoey', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1815, 'Vega', 18, 'nb', 'vega', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1816, 'Vevelstad', 18, 'nb', 'vevelstad', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1818, 'Herøy', 18, 'nb', 'heroy-no', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1820, 'Alstahaug', 18, 'nb', 'alstahaug', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1822, 'Leirfjord', 18, 'nb', 'leirfjord', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1824, 'Vefsn', 18, 'nb', 'vefsn', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1825, 'Grane', 18, 'nb', 'grane', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1826, 'Hattfjelldal', 18, 'nb', 'hattfjelldal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1827, 'Dønna', 18, 'nb', 'doenna', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1828, 'Nesna', 18, 'nb', 'nesna', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1832, 'Hemnes', 18, 'nb', 'hemnes', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1833, 'Rana', 18, 'nb', 'rana', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1834, 'Lurøy', 18, 'nb', 'luroey', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1835, 'Træna', 18, 'nb', 'traena', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1836, 'Rødøy', 18, 'nb', 'roedoey', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1837, 'Meløy', 18, 'nb', 'meloey', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1838, 'Gildeskål', 18, 'nb', 'gildeskaal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1839, 'Beiarn', 18, 'nb', 'beiarn', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1840, 'Saltdal', 18, 'nb', 'saltdal', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1841, 'Fauske', 18, 'nb', 'fauske', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1845, 'Sørfold', 18, 'nb', 'soerfold', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1848, 'Steigen', 18, 'nb', 'steigen', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1849, 'Hamarøy', 18, 'nb', 'hamaroey', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1850, 'Tysfjord', 18, 'nb', 'tysfjord', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1851, 'Lødingen', 18, 'nb', 'loedingen', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1852, 'Tjeldsund', 18, 'nb', 'tjeldsund', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1853, 'Evenes', 18, 'nb', 'evenes', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1854, 'Ballangen', 18, 'nb', 'ballangen', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1856, 'Røst', 18, 'nb', 'roest', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1857, 'Værøy', 18, 'nb', 'vaeroey', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1859, 'Flakstad', 18, 'nb', 'flakstad', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1860, 'Vestvågøy', 18, 'nb', 'vestvaagoey', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1865, 'Vågan', 18, 'nb', 'vaagan', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1866, 'Hadsel', 18, 'nb', 'hadsel', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1867, 'Bø', 18, 'nb', 'boe-no', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1868, 'Øksnes', 18, 'nb', 'oeksnes', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1870, 'Sortland', 18, 'nb', 'sortland', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1871, 'Andøy', 18, 'nb', 'andoey', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1874, 'Moskenes', 18, 'nb', 'moskenes', 300);
--INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1901, 'Harstad', 19, 'nb', 'harstad', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1903, 'Harstad', 19, 'nb', 'harstad', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1902, 'Tromsø', 19, 'nb', 'tromsoe', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1911, 'Kvæfjord', 19, 'nb', 'kvaefjord', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1913, 'Skånland', 19, 'nb', 'skaanland', 300);
--INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1915, 'Bjarkøy', 19, 'nb', 'bjarkoey', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1917, 'Ibestad', 19, 'nb', 'ibestad', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1919, 'Gratangen', 19, 'nb', 'gratangen', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1920, 'Lavangen', 19, 'nb', 'lavangen', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1922, 'Bardu', 19, 'nb', 'bardu', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1923, 'Salangen', 19, 'nb', 'salangen', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1924, 'Målselv', 19, 'nb', 'maalselv', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1925, 'Sørreisa', 19, 'nb', 'soerreisa', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1926, 'Dyrøy', 19, 'nb', 'dyroey', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1927, 'Tranøy', 19, 'nb', 'tranoey', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1928, 'Torsken', 19, 'nb', 'torsken', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1929, 'Berg', 19, 'nb', 'berg', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1931, 'Lenvik', 19, 'nb', 'lenvik', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1933, 'Balsfjord', 19, 'nb', 'balsfjord', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1936, 'Karlsøy', 19, 'nb', 'karlsoey', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1938, 'Lyngen', 19, 'nb', 'lyngen', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1939, 'Storfjord', 19, 'nb', 'storfjord', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1940, 'Gáivuotna Kåfjord', 19, 'nb', 'gaivuotna-kaafjord', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1941, 'Skjervøy', 19, 'nb', 'skjervoey', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1942, 'Nordreisa', 19, 'nb', 'nordreisa', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (1943, 'Kvænangen', 19, 'nb', 'kvaenangen', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (2002, 'Vardø', 20, 'nb', 'vardoe', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (2003, 'Vadsø', 20, 'nb', 'vadsoe', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (2004, 'Hammerfest', 20, 'nb', 'hammerfest', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (2011, 'Guovdageaidnu Kautokeino', 20, 'nb', 'guovdageaidnu-kautokeino', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (2012, 'Alta', 20, 'nb', 'alta', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (2014, 'Loppa', 20, 'nb', 'loppa', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (2015, 'Hasvik', 20, 'nb', 'hasvik', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (2017, 'Kvalsund', 20, 'nb', 'kvalsund', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (2018, 'Måsøy', 20, 'nb', 'maasoey', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (2019, 'Nordkapp', 20, 'nb', 'nordkapp', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (2020, 'Porsanger Porsángu Porsanki', 20, 'nb', 'porsanger-porsangu-porsanki', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (2021, 'Kárásjohka Karasjok', 20, 'nb', 'karasjohka-karasjok', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (2022, 'Lebesby', 20, 'nb', 'lebesby', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (2023, 'Gamvik', 20, 'nb', 'gamvik', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (2024, 'Berlevåg', 20, 'nb', 'berlevaag', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (2025, 'Deatnu Tana', 20, 'nb', 'deatnu-tana', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (2027, 'Unjárga Nesseby', 20, 'nb', 'unjarga-nesseby', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (2028, 'Båtsfjord', 20, 'nb', 'baatsfjord', 300);
INSERT INTO `location` (id, name, parent_id, default_language, slug, signatures_required) VALUES (2030, 'Sør-Varanger', 20, 'nb', 'soer-varanger', 300);


