/*
Copyright 2013 Kommunal- og regionaldepartementet.

This file is part of minsak.no.

Minsak.no is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License version 3 as published by the Free Software Foundation.

Minsak.no is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with minsak.no. If not, see http://www.gnu.org/licenses/gpl-3.0.html.
*/


SET NAMES utf8;
INSERT INTO `initiative` (id, location_id, title, text, created_time, status, status_time, user_id, image_type, image_file, image_credits, end_date) VALUES (1, 3, 'Flere trær i bakken', 'Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget.', UNIX_TIMESTAMP(NOW()), 'open', UNIX_TIMESTAMP(NOW()), 1, 'local', 'sample-initiative01', 'Dette bildet er tatt av Navn Navnesen / CC BY-NC-ND 2.0', UNIX_TIMESTAMP(NOW()) + 60*60*24*30);

INSERT INTO `initiative` (id, location_id, title, text, created_time, status, status_time, user_id, image_type, image_file, image_credits, end_date) VALUES (2, 3, 'Flere trikker til Kjelsås', 'Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget.', UNIX_TIMESTAMP(NOW()), 'open', UNIX_TIMESTAMP(NOW()), 1, 'local', 'sample-initiative02', 'Dette bildet er tatt av Navn Navnesen / CC BY-NC-ND 2.0', UNIX_TIMESTAMP(NOW()) + 60*60*24*30);

INSERT INTO `initiative` (id, location_id, title, text, created_time, status, status_time, user_id, image_type, image_file, image_credits, end_date) VALUES (3, 1601, 'Nye benker i byen', 'Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget.', UNIX_TIMESTAMP(NOW()), 'open', UNIX_TIMESTAMP(NOW()), 1, 'local', 'sample-initiative03', 'Dette bildet er tatt av Navn Navnesen / CC BY-NC-ND 2.0', UNIX_TIMESTAMP(NOW()) + 60*60*24*30);

INSERT INTO `initiative` (id, location_id, title, text, created_time, status, status_time, user_id, image_type, image_file, image_credits, end_date) VALUES (4, 1103, 'Graffiti på togstasjonen', 'Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget.', UNIX_TIMESTAMP(NOW()), 'open', UNIX_TIMESTAMP(NOW()), 1, 'local', 'sample-initiative04', 'Dette bildet er tatt av Navn Navnesen / CC BY-NC-ND 2.0', UNIX_TIMESTAMP(NOW()) + 60*60*24*30);

INSERT INTO `initiative` (id, location_id, title, text, created_time, status, status_time, user_id, image_type, image_file, image_credits, end_date) VALUES (5, 1103, 'Vekk med supplybåtene!', 'Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget.', UNIX_TIMESTAMP(NOW()), 'open', UNIX_TIMESTAMP(NOW()), 1, 'local', 'sample-initiative05', 'Dette bildet er tatt av Navn Navnesen / CC BY-NC-ND 2.0', UNIX_TIMESTAMP(NOW()) + 60*60*24*30);

INSERT INTO `initiative` (id, location_id, title, text, created_time, status, status_time, user_id, image_type, image_file, image_credits, end_date) VALUES (6, 1103, 'Varmekabler i bratte bakker!', 'Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget.', UNIX_TIMESTAMP(NOW()), 'open', UNIX_TIMESTAMP(NOW()), 1, 'local', 'sample-initiative06', 'Dette bildet er tatt av Navn Navnesen / CC BY-NC-ND 2.0', UNIX_TIMESTAMP(NOW()) + 60*60*24*30);

INSERT INTO `initiative` (id, location_id, title, text, created_time, status, status_time, user_id, image_type, image_file, image_credits, end_date) VALUES (7, 1201, 'Hold veggene rene!', 'Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget.', UNIX_TIMESTAMP(NOW()), 'open', UNIX_TIMESTAMP(NOW()), 1, 'local', 'sample-initiative07', 'Dette bildet er tatt av Navn Navnesen / CC BY-NC-ND 2.0', UNIX_TIMESTAMP(NOW()) + 60*60*24*30);

INSERT INTO `initiative` (id, location_id, title, text, created_time, status, status_time, user_id, image_type, image_file, image_credits, end_date) VALUES (8, 1219, 'Større fiskekvoter!', 'Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget.', UNIX_TIMESTAMP(NOW()), 'open', UNIX_TIMESTAMP(NOW()), 1, 'local', 'sample-initiative08', 'Dette bildet er tatt av Navn Navnesen / CC BY-NC-ND 2.0', UNIX_TIMESTAMP(NOW()) + 60*60*24*30);
INSERT INTO `initiative` (id, location_id, title, text, created_time, status, status_time, user_id, image_type, image_file, image_credits, end_date) VALUES (9, 1219, 'Enda større fiskekvoter!', 'Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget.', UNIX_TIMESTAMP(NOW()), 'open', UNIX_TIMESTAMP(NOW()), 1, 'local', 'sample-initiative08', 'Dette bildet er tatt av Navn Navnesen / CC BY-NC-ND 2.0', UNIX_TIMESTAMP(NOW()) + 60*60*24*30);
INSERT INTO `initiative` (id, location_id, title, text, created_time, status, status_time, user_id, image_type, image_file, image_credits, end_date) VALUES (10, 1219, 'Enda mindre fiskekvoter!', 'Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget.', UNIX_TIMESTAMP(NOW()), 'open', UNIX_TIMESTAMP(NOW()), 1, 'local', 'sample-initiative08', 'Dette bildet er tatt av Navn Navnesen / CC BY-NC-ND 2.0', UNIX_TIMESTAMP(NOW()) + 60*60*24*30);
INSERT INTO `initiative` (id, location_id, title, text, created_time, status, status_time, user_id, image_type, image_file, image_credits, end_date) VALUES (11, 1219, 'Ingen fiskekvoter!', 'Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget.', UNIX_TIMESTAMP(NOW()), 'open', UNIX_TIMESTAMP(NOW()), 1, 'local', 'sample-initiative08', 'Dette bildet er tatt av Navn Navnesen / CC BY-NC-ND 2.0', UNIX_TIMESTAMP(NOW()) + 60*60*24*30);
INSERT INTO `initiative` (id, location_id, title, text, created_time, status, status_time, user_id, image_type, image_file, image_credits, end_date) VALUES (12, 1219, 'Fiskekvoter!', 'Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget.', UNIX_TIMESTAMP(NOW()), 'open', UNIX_TIMESTAMP(NOW()), 1, 'local', 'sample-initiative08', 'Dette bildet er tatt av Navn Navnesen / CC BY-NC-ND 2.0', UNIX_TIMESTAMP(NOW()) + 60*60*24*30);
INSERT INTO `initiative` (id, location_id, title, text, created_time, status, status_time, user_id, image_type, image_file, image_credits, end_date) VALUES (13, 1219, 'Bare fiskekvoter!', 'Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget.', UNIX_TIMESTAMP(NOW()), 'open', UNIX_TIMESTAMP(NOW()), 1, 'local', 'sample-initiative08', 'Dette bildet er tatt av Navn Navnesen / CC BY-NC-ND 2.0', UNIX_TIMESTAMP(NOW()) + 60*60*24*30);
INSERT INTO `initiative` (id, location_id, title, text, created_time, status, status_time, user_id, image_type, image_file, image_credits, end_date) VALUES (14, 1219, 'Flere fiskekvoter!', 'Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget.', UNIX_TIMESTAMP(NOW()), 'open', UNIX_TIMESTAMP(NOW()), 1, 'local', 'sample-initiative08', 'Dette bildet er tatt av Navn Navnesen / CC BY-NC-ND 2.0', UNIX_TIMESTAMP(NOW()) + 60*60*24*30);
INSERT INTO `initiative` (id, location_id, title, text, created_time, status, status_time, user_id, image_type, image_file, image_credits, end_date) VALUES (15, 1219, 'Avskaff fiskekvoter!', 'Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget.', UNIX_TIMESTAMP(NOW()), 'open', UNIX_TIMESTAMP(NOW()), 1, 'local', 'sample-initiative08', 'Dette bildet er tatt av Navn Navnesen / CC BY-NC-ND 2.0', UNIX_TIMESTAMP(NOW()) + 60*60*24*30);
INSERT INTO `initiative` (id, location_id, title, text, created_time, status, status_time, user_id, image_type, image_file, image_credits, end_date) VALUES (16, 1219, 'Ingen fiskekvoter!', 'Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget.', UNIX_TIMESTAMP(NOW()), 'open', UNIX_TIMESTAMP(NOW()), 1, 'local', 'sample-initiative08', 'Dette bildet er tatt av Navn Navnesen / CC BY-NC-ND 2.0', UNIX_TIMESTAMP(NOW()) + 60*60*24*30);
INSERT INTO `initiative` (id, location_id, title, text, created_time, status, status_time, user_id, image_type, image_file, image_credits, end_date) VALUES (17, 1219, 'Tolv fiskekvoter!', 'Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget.', UNIX_TIMESTAMP(NOW()), 'open', UNIX_TIMESTAMP(NOW()), 1, 'local', 'sample-initiative08', 'Dette bildet er tatt av Navn Navnesen / CC BY-NC-ND 2.0', UNIX_TIMESTAMP(NOW()) + 60*60*24*30);
INSERT INTO `initiative` (id, location_id, title, text, created_time, status, status_time, user_id, image_type, image_file, image_credits, end_date) VALUES (18, 1219, 'Alltid fiskekvoter!', 'Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget.', UNIX_TIMESTAMP(NOW()), 'open', UNIX_TIMESTAMP(NOW()), 1, 'local', 'sample-initiative08', 'Dette bildet er tatt av Navn Navnesen / CC BY-NC-ND 2.0', UNIX_TIMESTAMP(NOW()) + 60*60*24*30);
INSERT INTO `initiative` (id, location_id, title, text, created_time, status, status_time, user_id, image_type, image_file, image_credits, end_date) VALUES (19, 1219, 'Store fiskekvoter!', 'Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget. Dette er brødteksten for forslaget.', UNIX_TIMESTAMP(NOW()), 'open', UNIX_TIMESTAMP(NOW()), 1, 'local', 'sample-initiative08', 'Dette bildet er tatt av Navn Navnesen / CC BY-NC-ND 2.0', UNIX_TIMESTAMP(NOW()) + 60*60*24*30);


INSERT INTO `signature` (initiative_id, name, address1, address2, area_code, moderated) VALUES (1, 'Ola Nordmann',  'Adresse 1', 'Adresse 2', 4006, 'accepted');
INSERT INTO `signature` (initiative_id, name, address1, address2, area_code, moderated) VALUES (1, 'Kari Nordmann', 'Adresse 1', 'Adresse 2', 4006, 'accepted');
INSERT INTO `signature` (initiative_id, name, address1, address2, area_code, moderated) VALUES (1, 'Jens Nordmann', 'Adresse 1', 'Adresse 2', 4006, 'accepted');

INSERT INTO `signature` (initiative_id, name, address1, address2, area_code, moderated) VALUES (2, 'Ola Nordmann',  'Adresse 1', 'Adresse 2', 4006, 'accepted');
INSERT INTO `signature` (initiative_id, name, address1, address2, area_code, moderated) VALUES (2, 'Kari Nordmann', 'Adresse 1', 'Adresse 2', 4006, 'accepted');

INSERT INTO `signature` (initiative_id, name, address1, address2, area_code, moderated) VALUES (3, 'Ola Nordmann',  'Adresse 1', 'Adresse 2', 4006, 'accepted');


INSERT INTO `initiative_comment` (initiative_id, name, text, created_time) VALUES (1, 'Ola Nordmann', 'Dette er en kommentar.', UNIX_TIMESTAMP(NOW())+60*60);
INSERT INTO `initiative_comment` (initiative_id, name, text, created_time) VALUES (1, 'Kari Nordmann', 'Dette er enda en kommentar.', UNIX_TIMESTAMP(NOW())+60*60*2);

INSERT INTO `initiative_comment` (initiative_id, name, text, created_time) VALUES (2, 'Ola Nordmann', 'Dette er en kommentar.', UNIX_TIMESTAMP(NOW())+60*60);
